{% set version = "0.18.1" %}

package:
  name: docutils
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/docutils/docutils-{{ version }}.tar.gz
  sha256: 679987caf361a7539d76e584cbeddc311e3aee937877c87346f31debc63e9d06

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - docutils
    - docutils.languages
    - docutils.parsers
    - docutils.parsers.rst
    - docutils.parsers.rst.directives
    - docutils.parsers.rst.languages
    - docutils.readers
    - docutils.transforms
    - docutils.utils
    - docutils.utils.math
    - docutils.writers
    - docutils.writers.html4css1
    - docutils.writers.html5_polyglot
    - docutils.writers.latex2e
    - docutils.writers.odf_odt
    - docutils.writers.pep_html
    - docutils.writers.s5_html
    - docutils.writers.xetex

about:
  home: http://docutils.sourceforge.net/
  # docutils itself contains GPL-3.0-or-later licensed code as stated in COPYING.txt
  # but the relevant file tools/editors/emacs/rst.el is not shipped as part of the package.
  license: CC-PDDC AND BSD-3-Clause AND BSD-2-Clause AND ZPL-2.1
  license_file: COPYING.txt
  summary: Docutils -- Python Documentation Utilities
  description: |
    Docutils is an open-source text processing system for processing plaintext
    documentation into useful formats, such as HTML, LaTeX, man-pages, open-
    document, or XML.
  doc_url: http://docutils.sourceforge.net/docs/index.html
  doc_source_url: https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docs/index.txt
  dev_url: http://svn.code.sf.net/p/docutils/code

extra:
  recipe-maintainers:
    - pmlandwehr
    - nehaljwani
    - ocefpaf
