{%set name = "docutils" %}
{%set version = "0.14rc1" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "7ee93a6fbab0f46bdda4d94384de40a04bbbbb53dbd019ce0fbbbfed22f6589a" %}
{%set build_num = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - docutils
    - docutils.languages
    - docutils.parsers
    - docutils.parsers.rst
    - docutils.parsers.rst.directives
    - docutils.parsers.rst.languages
    - docutils.readers
    - docutils.transforms
    - docutils.utils
    - docutils.utils.math
    - docutils.writers
    - docutils.writers.html4css1
    - docutils.writers.latex2e
    - docutils.writers.odf_odt
    - docutils.writers.pep_html
    - docutils.writers.s5_html
    - docutils.writers.xetex

about:
  home: http://docutils.sourceforge.net/
  license: Public Domain Dedictation and BSD 2-Clause and PSF 2.1.1 and GPL 3.0
  summary: 'Docutils -- Python Documentation Utilities'
  dev_url: http://docutils.sourceforge.net/

extra:
  recipe-maintainers:
    - pmlandwehr
